name: Analyseur Sectoriel Continu

on:
  schedule:
    # Exécution toutes les 3 heures, 7 jours sur 7, 24h/24
    - cron: '0 */3 * * *'
  workflow_dispatch: # Permet de le lancer manuellement quand tu veux

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code du dépôt
        uses: actions/checkout@v4

      - name: Configurer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installer les bibliothèques
        run: |
          pip install yfinance pandas ta requests lxml html5lib

      - name: Exécuter l'Analyse Mondiale
        env:
          TOKEN_TELEGRAM: ${{ secrets.TOKEN_TELEGRAM }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python bot.py
